name: Trigger Send Emails

# runs every 2 minutes
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  hit-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke send‑emails endpoint
        run: |
          curl -fsS https://email-automation.vercel.app/api/send-emails \
            -H "Authorization: Bearer ${{ secrets.SCHEDULER_TOKEN }}"
